#
# ███████╗███████╗███████╗██╗  ██╗     ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗ 
# ██╔════╝██╔════╝██╔════╝██║  ██║    ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝ 
# ███████╗█████╗  ███████╗███████║    ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
# ╚════██║██╔══╝  ╚════██║██╔══██║    ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
# ███████║███████╗███████║██║  ██║    ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
# ╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝     ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝ 
#
# Smart session manager for the terminal
# https://github.com/joshmedeski/sesh

sort_order = ["tmux", "config"]

[default_session]
startup_command = "ls"
preview_command = "eza --all --git --icons --color=always {}"
# startup_command_ignore_dirs = ["~/repos", "~/.config"]

[[session]]
name = "home"
path = "~"
disable_startup_command = true

[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "ls"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "hammerspoon"
path = "~/.config/hammerspoon-config"
startup_command = "git status"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "nvim"
path = "~/dotfiles/config/.config/nvim"
startup_command = "ls"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "quartz"
path = "~/Desktop/2. AREAS/Digital Garden/quartz"
startup_command = "nvim content/index.md"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "brain"
path = "~/Desktop/2. AREAS/Second Brain"
startup_command = "ls"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "skilledin"
path = "~/Desktop/1. PROJECTS/skilledin"
startup_command = "ls"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "gtdust"
path = "~/Desktop/1. PROJECTS/gtdust"
startup_command = "ls"
preview_command = "eza --all --git --icons --color=always {}"
