after-login-command = []

after-startup-command = [
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0' # Activate JankyBorders
]

start-at-login = true 

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 0
inner.vertical =   0
outer.left =       0
outer.bottom =     0
outer.top =        0
outer.right =      0

# =================================================================
#
# Assign apps on particular workspaces
#
# Use this command to get IDs of running applications:
#   aerospace list-apps
#
# =================================================================

[[on-window-detected]]
if.app-id = 'md.obsidian'				# Obsidian
run = 'move-node-to-workspace Notes'

[[on-window-detected]]
if.app-id = 'notion.id'					# Notion
run = 'move-node-to-workspace Notes'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'				# Google Chrome
run = 'move-node-to-workspace Browser'

[[on-window-detected]]
if.app-id = 'org.mozilla.floorp'			# Floorp
run = 'move-node-to-workspace Browser'

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'			# WhatsApp
run = 'move-node-to-workspace Communication'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'			# Slack
run = 'move-node-to-workspace Communication'

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'				# Discord
run = 'move-node-to-workspace Communication'

[[on-window-detected]]
if.app-id = 'com.cron.electron'				# Notion Calendar
run = 'move-node-to-workspace 9-Calendar'

[[on-window-detected]]
if.app-id = 'com.googlecode.iterm2'			# iTerm2 
run = 'move-node-to-workspace Terminal'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'			# Ghostty
run = 'move-node-to-workspace Terminal'

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'			# VS Code
run = ['layout floating', 'move-node-to-workspace Editor']

[[on-window-detected]]
if.app-id = 'com.todesktop.230313mzl4w4u92'		# Cursor
run = ['layout floating', 'move-node-to-workspace Editor']

[[on-window-detected]]
if.app-id = 'com.todoist.mac.Todoist'			# Todoist
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.Notes'				# Apple Notes
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.finder'				# Finder
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'		# System Settings / Preferences
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.raycast.macos'				# Raycast
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'org.hammerspoon.Hammerspoon'		# Hammerspoon
run = ['layout floating']

[[on-window-detected]]					# Make all the other applications / windows float in 0-Other Workspace
check-further-callbacks = true
run = ['layout floating', 'move-node-to-workspace 0-Other']

