#
# ███████╗███████╗███████╗██╗  ██╗     ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗ 
# ██╔════╝██╔════╝██╔════╝██║  ██║    ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝ 
# ███████╗█████╗  ███████╗███████║    ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
# ╚════██║██╔══╝  ╚════██║██╔══██║    ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
# ███████║███████╗███████║██║  ██║    ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
# ╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝     ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝ 
#
# Smart session manager for the terminal
# https://github.com/joshmedeski/sesh

sort_order = ["tmux", "config"]
# sort_order = ["tmux", "config", "tmuxinator", "zoxide"]

# default

[default_session]
startup_command = "ls"
preview_command = "eza --all --git --icons --color=always {}"
# startup_command_ignore_dirs = ["~/repos", "~/.config"]

[[session]]
name = "home (~)"
path = "~"
disable_startup_command = true
# startup_command = "l"


[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "skilledin"
path = "~/Desktop/1. PROJECTS/skilledin"
startup_command = "ls"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "tmux config"
path = "~"
startup_command = "nvim .tmux.conf"
preview_command = "bat --color=always ~/.tmux.conf"

[[session]]
name = "zsh config"
path = "~"
startup_command = "nvim .zshrc"
preview_command = "bat --color=always ~/.zshrc"

[[session]]
name = "hammerspoon config"
path = "~/.config/hammerspoon-config"
startup_command = "git status"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "sesh config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "eza --all --git --icons --color=always {}"
