#
# ████████╗███╗   ███╗██╗   ██╗██╗  ██╗
# ╚══██╔══╝████╗ ████║██║   ██║╚██╗██╔╝
#    ██║   ██╔████╔██║██║   ██║ ╚███╔╝
#    ██║   ██║╚██╔╝██║██║   ██║ ██╔██╗
#    ██║   ██║ ╚═╝ ██║╚██████╔╝██╔╝ ██╗
#    ╚═╝   ╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═╝
#
# Terminal multiplexer
# https://github.com/tmux/tmux


################################################# BASICS ######################################################
# Easy config reload (prefix + r)
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

set -g base-index 1          # start indexing windows at 1 instead of 0
set -g detach-on-destroy off # don't exit from tmux when closing a session
set -g escape-time 0         # zero-out escape time delay
set -g history-limit 1000000 # increase history size (from 2,000)
set -g mouse on              # enable mouse support
set -g renumber-windows on   # renumber all windows when any window is closed
set -g set-clipboard on      # use system clipboard
set -g status-interval 3     # update the status bar every 3 seconds

# Colors
set -g default-terminal "tmux-256color"

# SESH (tmux Session Manager)
bind-key "T" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""


############################################# PLUGINS #########################################################
# Plugins are powered by TPM: https://github.com/tmux-plugins/tpm
# You can find new plugins here: https://github.com/tmux-plugins/list
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

#### TMUX GURVBOX THEME ####
# Find more info here: https://github.com/egel/tmux-gruvbox
set -g @plugin 'egel/tmux-gruvbox'

#### TMUX NERD FOND WINDWOW NAME ####
# This plugin automatically add Nerd Font support to your tmux window names
# https://github.com/joshmedeski/tmux-nerd-font-window-name
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'

#### TMUX MODE INDICATOR ####
# This plugin displays prompt indicating currently active tmux mode
# https://github.com/MunifTanjim/tmux-mode-indicator
set -g @plugin 'MunifTanjim/tmux-mode-indicator'
# prompt to display when tmux prefix key is pressed
set -g @mode_indicator_prefix_prompt ' LEADER '
# style values for prefix prompt
set -g @mode_indicator_prefix_mode_style 'bg=red,fg=white'


############################################# THEMING #########################################################
# Configure the Gruvbox plugin
set -g @tmux-gruvbox 'dark256'


############################################# STATUS LINE #####################################################
# General statusline customisation
set-option -g status-position bottom
set -g status-style 'bg=terminal'

# Border above statusline
set -g pane-border-format ""
set -g pane-border-status bottom
set -g pane-border-style fg=colour0
set -g pane-active-border-style fg=colour0

# Gruvbox statusline customisation
set -g @tmux-gruvbox-right-status-x '%m/%d/%Y'
set -g @tmux-gruvbox-right-status-y '%I:%M %p'
set -g @tmux-gruvbox-right-status-z 'ishahroz #{tmux_mode_indicator}'


############################################### TPM ######################################################
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
